import os

TG_TOKEN=os.getenv('TG_TOKEN')
SPOTIFY_CLIENT_ID=os.getenv('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_SECRET=os.getenv('SPOTIFY_CLIENT_SECRET')
ES_ENDPOINT=os.getenv('ES_ENDPOINT')
ES_KEY=os.getenv('ES_KEY')
ES_KEY_DOCKER=os.getenv('ES_KEY_DOCKER')
ES_API_ID=os.getenv('ES_API_ID')
GENIUS_CLIENT_ID=os.getenv('GENIUS_CLIENT_ID')
GENIUS_CLIENT_SECRET=os.getenv('GENIUS_CLIENT_SECRET')
GENIUS_CLIENT_ACCESS_TOKEN=os.getenv('GENIUS_CLIENT_ACCESS_TOKEN')
